ONE_MINUTE = 60
ONE_HOUR = 3600
ONE_DAY = 86400
ONE_WEEK = 604800
ONE_MONTH = 2592000
ONE_YEAR = 31536000

HALF_AN_HOUR = ONE_HOUR / 2
QUARTER_HOUR = ONE_HOUR / 4
TWO_HOURS = ONE_HOUR * 2
THREE_HOURS = ONE_HOUR * 3
FOUR_HOURS = ONE_HOUR * 4
FIVE_HOURS = ONE_HOUR * 5
SIX_HOURS = ONE_HOUR * 6
SEVEN_HOURS = ONE_HOUR * 7
EIGHT_HOURS = ONE_HOUR * 8
NINE_HOURS = ONE_HOUR * 9
TEN_HOURS = ONE_HOUR * 10

THREE_MINUTES = ONE_MINUTE * 3
FIVE_MINUTES = ONE_MINUTE * 5
TEN_MINUTES = ONE_MINUTE * 10
FIFTEEN_MINUTES = QUARTER_HOUR
THIRTY_MINUTES = HALF_AN_HOUR

TWO_DAYS = 2 * ONE_DAY
THREE_DAYS = 3 * ONE_DAY
FOUR_DAYS = 4 * ONE_DAY
FIVE_DAYS = 5 * ONE_DAY
SIX_DAYS = 6 * ONE_DAY
SEVEN_DAYS = ONE_WEEK
